name = "kwenta-base-sepolia-quanto-spot"
version = "0.0.1"
description = "Deploy Quanto Perps & Custom Spot Market on Base Sepolia and Register Markets with Kwenta Deployment of Synthetix v3 Core"
preset = "andromeda"
include = [
    "tomls/kwenta-core.toml",
    "tomls/markets/spot-factory.toml",
    "tomls/omnibus-base-sepolia-andromeda/spot/eth.toml",
]
